/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVendasRouteImport } from './routes/app.vendas'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPrecificacaoRouteImport } from './routes/app.precificacao'
import { Route as AppPlanoAcaoRouteImport } from './routes/app.plano-acao'
import { Route as AppPendenciasRouteImport } from './routes/app.pendencias'
import { Route as AppOrcamentoRouteImport } from './routes/app.orcamento'
import { Route as AppKpisRouteImport } from './routes/app.kpis'
import { Route as AppJornadaRouteImport } from './routes/app.jornada'
import { Route as AppImportacoesRouteImport } from './routes/app.importacoes'
import { Route as AppFluxoCaixaRouteImport } from './routes/app.fluxo-caixa'
import { Route as AppExecutivoRouteImport } from './routes/app.executivo'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppDocumentosRouteImport } from './routes/app.documentos'
import { Route as AppDiagnosticoRouteImport } from './routes/app.diagnostico'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppContasReceberRouteImport } from './routes/app.contas-receber'
import { Route as AppContasPagarRouteImport } from './routes/app.contas-pagar'
import { Route as AppConsultoriaRouteImport } from './routes/app.consultoria'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppCentroCustosRouteImport } from './routes/app.centro-custos'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppEmpresaIdRouteImport } from './routes/app.empresa.$id'
import { Route as AppCrmIdRouteImport } from './routes/app.crm.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasRoute = AppVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPrecificacaoRoute = AppPrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanoAcaoRoute = AppPlanoAcaoRouteImport.update({
  id: '/plano-acao',
  path: '/plano-acao',
  getParentRoute: () => AppRoute,
} as any)
const AppPendenciasRoute = AppPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoRoute = AppOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AppRoute,
} as any)
const AppKpisRoute = AppKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => AppRoute,
} as any)
const AppJornadaRoute = AppJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacoesRoute = AppImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutivoRoute = AppExecutivoRouteImport.update({
  id: '/executivo',
  path: '/executivo',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDiagnosticoRoute = AppDiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppContasReceberRoute = AppContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => AppRoute,
} as any)
const AppContasPagarRoute = AppContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultoriaRoute = AppConsultoriaRouteImport.update({
  id: '/consultoria',
  path: '/consultoria',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCentroCustosRoute = AppCentroCustosRouteImport.update({
  id: '/centro-custos',
  path: '/centro-custos',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppPendenciasRoute = AppPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AppRoute,
} as any)
const AppJornadaRoute = AppJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresaIdRoute = AppEmpresaIdRouteImport.update({
  id: '/empresa/$id',
  path: '/empresa/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIdRoute = AppCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/centro-custos': typeof AppCentroCustosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/consultoria': typeof AppConsultoriaRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/executivo': typeof AppExecutivoRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/importacoes': typeof AppImportacoesRoute
  '/app/jornada': typeof AppJornadaRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/pendencias': typeof AppPendenciasRoute
  '/app/plano-acao': typeof AppPlanoAcaoRoute
  '/app/precificacao': typeof AppPrecificacaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/': typeof AppIndexRoute
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/empresa/$id': typeof AppEmpresaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/centro-custos': typeof AppCentroCustosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/consultoria': typeof AppConsultoriaRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/executivo': typeof AppExecutivoRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/importacoes': typeof AppImportacoesRoute
  '/app/jornada': typeof AppJornadaRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/pendencias': typeof AppPendenciasRoute
  '/app/plano-acao': typeof AppPlanoAcaoRoute
  '/app/precificacao': typeof AppPrecificacaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app': typeof AppIndexRoute
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/empresa/$id': typeof AppEmpresaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/centro-custos': typeof AppCentroCustosRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/consultoria': typeof AppConsultoriaRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/crm': typeof AppCrmRouteWithChildren
  '/app/diagnostico': typeof AppDiagnosticoRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/executivo': typeof AppExecutivoRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/importacoes': typeof AppImportacoesRoute
  '/app/jornada': typeof AppJornadaRoute
  '/app/kpis': typeof AppKpisRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/pendencias': typeof AppPendenciasRoute
  '/app/plano-acao': typeof AppPlanoAcaoRoute
  '/app/precificacao': typeof AppPrecificacaoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/vendas': typeof AppVendasRoute
  '/app/': typeof AppIndexRoute
  '/app/crm/$id': typeof AppCrmIdRoute
  '/app/empresa/$id': typeof AppEmpresaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/agenda'
    | '/app/centro-custos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/consultoria'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/crm'
    | '/app/diagnostico'
    | '/app/documentos'
    | '/app/estoque'
    | '/app/executivo'
    | '/app/fluxo-caixa'
    | '/app/importacoes'
    | '/app/jornada'
    | '/app/kpis'
    | '/app/orcamento'
    | '/app/pendencias'
    | '/app/plano-acao'
    | '/app/precificacao'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app/'
    | '/app/crm/$id'
    | '/app/empresa/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/agenda'
    | '/app/centro-custos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/consultoria'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/crm'
    | '/app/diagnostico'
    | '/app/documentos'
    | '/app/estoque'
    | '/app/executivo'
    | '/app/fluxo-caixa'
    | '/app/importacoes'
    | '/app/jornada'
    | '/app/kpis'
    | '/app/orcamento'
    | '/app/pendencias'
    | '/app/plano-acao'
    | '/app/precificacao'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app'
    | '/app/crm/$id'
    | '/app/empresa/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/agenda'
    | '/app/centro-custos'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/consultoria'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/crm'
    | '/app/diagnostico'
    | '/app/documentos'
    | '/app/estoque'
    | '/app/executivo'
    | '/app/fluxo-caixa'
    | '/app/importacoes'
    | '/app/jornada'
    | '/app/kpis'
    | '/app/orcamento'
    | '/app/pendencias'
    | '/app/plano-acao'
    | '/app/precificacao'
    | '/app/relatorios'
    | '/app/vendas'
    | '/app/'
    | '/app/crm/$id'
    | '/app/empresa/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendas': {
      id: '/app/vendas'
      path: '/vendas'
      fullPath: '/app/vendas'
      preLoaderRoute: typeof AppVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/precificacao': {
      id: '/app/precificacao'
      path: '/precificacao'
      fullPath: '/app/precificacao'
      preLoaderRoute: typeof AppPrecificacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plano-acao': {
      id: '/app/plano-acao'
      path: '/plano-acao'
      fullPath: '/app/plano-acao'
      preLoaderRoute: typeof AppPlanoAcaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pendencias': {
      id: '/app/pendencias'
      path: '/pendencias'
      fullPath: '/app/pendencias'
      preLoaderRoute: typeof AppPendenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orcamento': {
      id: '/app/orcamento'
      path: '/orcamento'
      fullPath: '/app/orcamento'
      preLoaderRoute: typeof AppOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kpis': {
      id: '/app/kpis'
      path: '/kpis'
      fullPath: '/app/kpis'
      preLoaderRoute: typeof AppKpisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jornada': {
      id: '/app/jornada'
      path: '/jornada'
      fullPath: '/app/jornada'
      preLoaderRoute: typeof AppJornadaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importacoes': {
      id: '/app/importacoes'
      path: '/importacoes'
      fullPath: '/app/importacoes'
      preLoaderRoute: typeof AppImportacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fluxo-caixa': {
      id: '/app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/app/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/executivo': {
      id: '/app/executivo'
      path: '/executivo'
      fullPath: '/app/executivo'
      preLoaderRoute: typeof AppExecutivoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/diagnostico': {
      id: '/app/diagnostico'
      path: '/diagnostico'
      fullPath: '/app/diagnostico'
      preLoaderRoute: typeof AppDiagnosticoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-receber': {
      id: '/app/contas-receber'
      path: '/contas-receber'
      fullPath: '/app/contas-receber'
      preLoaderRoute: typeof AppContasReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-pagar': {
      id: '/app/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/app/contas-pagar'
      preLoaderRoute: typeof AppContasPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultoria': {
      id: '/app/consultoria'
      path: '/consultoria'
      fullPath: '/app/consultoria'
      preLoaderRoute: typeof AppConsultoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/centro-custos': {
      id: '/app/centro-custos'
      path: '/centro-custos'
      fullPath: '/app/centro-custos'
      preLoaderRoute: typeof AppCentroCustosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresa/$id': {
      id: '/app/empresa/$id'
      path: '/empresa/$id'
      fullPath: '/app/empresa/$id'
      preLoaderRoute: typeof AppEmpresaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm/$id': {
      id: '/app/crm/$id'
      path: '/$id'
      fullPath: '/app/crm/$id'
      preLoaderRoute: typeof AppCrmIdRouteImport
      parentRoute: typeof AppCrmRoute
    }
  }
}

interface AppCrmRouteChildren {
  AppCrmIdRoute: typeof AppCrmIdRoute
}

const AppCrmRouteChildren: AppCrmRouteChildren = {
  AppCrmIdRoute: AppCrmIdRoute,
}

const AppCrmRouteWithChildren =
  AppCrmRoute._addFileChildren(AppCrmRouteChildren)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppCentroCustosRoute: typeof AppCentroCustosRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConsultoriaRoute: typeof AppConsultoriaRoute
  AppContasPagarRoute: typeof AppContasPagarRoute
  AppContasReceberRoute: typeof AppContasReceberRoute
  AppCrmRoute: typeof AppCrmRouteWithChildren
  AppDiagnosticoRoute: typeof AppDiagnosticoRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppExecutivoRoute: typeof AppExecutivoRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppImportacoesRoute: typeof AppImportacoesRoute
  AppJornadaRoute: typeof AppJornadaRoute
  AppKpisRoute: typeof AppKpisRoute
  AppOrcamentoRoute: typeof AppOrcamentoRoute
  AppPendenciasRoute: typeof AppPendenciasRoute
  AppPlanoAcaoRoute: typeof AppPlanoAcaoRoute
  AppPrecificacaoRoute: typeof AppPrecificacaoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppVendasRoute: typeof AppVendasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmpresaIdRoute: typeof AppEmpresaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppCentroCustosRoute: AppCentroCustosRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConsultoriaRoute: AppConsultoriaRoute,
  AppContasPagarRoute: AppContasPagarRoute,
  AppContasReceberRoute: AppContasReceberRoute,
  AppCrmRoute: AppCrmRouteWithChildren,
  AppDiagnosticoRoute: AppDiagnosticoRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppExecutivoRoute: AppExecutivoRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppImportacoesRoute: AppImportacoesRoute,
  AppJornadaRoute: AppJornadaRoute,
  AppKpisRoute: AppKpisRoute,
  AppOrcamentoRoute: AppOrcamentoRoute,
  AppPendenciasRoute: AppPendenciasRoute,
  AppPlanoAcaoRoute: AppPlanoAcaoRoute,
  AppPrecificacaoRoute: AppPrecificacaoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppVendasRoute: AppVendasRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmpresaIdRoute: AppEmpresaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
