/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppOrcamentoRouteImport } from './routes/app.orcamento'
import { Route as AppFluxoCaixaRouteImport } from './routes/app.fluxo-caixa'
import { Route as AppEstoqueRouteImport } from './routes/app.estoque'
import { Route as AppContasReceberRouteImport } from './routes/app.contas-receber'
import { Route as AppContasPagarRouteImport } from './routes/app.contas-pagar'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/app.clientes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoRoute = AppOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxoCaixaRoute = AppFluxoCaixaRouteImport.update({
  id: '/fluxo-caixa',
  path: '/fluxo-caixa',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppContasReceberRoute = AppContasReceberRouteImport.update({
  id: '/contas-receber',
  path: '/contas-receber',
  getParentRoute: () => AppRoute,
} as any)
const AppContasPagarRoute = AppContasPagarRouteImport.update({
  id: '/contas-pagar',
  path: '/contas-pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contas-pagar': typeof AppContasPagarRoute
  '/app/contas-receber': typeof AppContasReceberRoute
  '/app/estoque': typeof AppEstoqueRoute
  '/app/fluxo-caixa': typeof AppFluxoCaixaRoute
  '/app/orcamento': typeof AppOrcamentoRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/estoque'
    | '/app/fluxo-caixa'
    | '/app/orcamento'
    | '/app/relatorios'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/estoque'
    | '/app/fluxo-caixa'
    | '/app/orcamento'
    | '/app/relatorios'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/clientes'
    | '/app/configuracoes'
    | '/app/contas-pagar'
    | '/app/contas-receber'
    | '/app/estoque'
    | '/app/fluxo-caixa'
    | '/app/orcamento'
    | '/app/relatorios'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orcamento': {
      id: '/app/orcamento'
      path: '/orcamento'
      fullPath: '/app/orcamento'
      preLoaderRoute: typeof AppOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fluxo-caixa': {
      id: '/app/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/app/fluxo-caixa'
      preLoaderRoute: typeof AppFluxoCaixaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/estoque': {
      id: '/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-receber': {
      id: '/app/contas-receber'
      path: '/contas-receber'
      fullPath: '/app/contas-receber'
      preLoaderRoute: typeof AppContasReceberRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contas-pagar': {
      id: '/app/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/app/contas-pagar'
      preLoaderRoute: typeof AppContasPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContasPagarRoute: typeof AppContasPagarRoute
  AppContasReceberRoute: typeof AppContasReceberRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFluxoCaixaRoute: typeof AppFluxoCaixaRoute
  AppOrcamentoRoute: typeof AppOrcamentoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContasPagarRoute: AppContasPagarRoute,
  AppContasReceberRoute: AppContasReceberRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFluxoCaixaRoute: AppFluxoCaixaRoute,
  AppOrcamentoRoute: AppOrcamentoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
